/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pcgod.mumbleclient.jni;

public interface celtConstants {
  public final static int CELT_OK = 0;
  public final static int CELT_BAD_ARG = -1;
  public final static int CELT_INVALID_MODE = -2;
  public final static int CELT_INTERNAL_ERROR = -3;
  public final static int CELT_CORRUPTED_DATA = -4;
  public final static int CELT_UNIMPLEMENTED = -5;
  public final static int CELT_INVALID_STATE = -6;
  public final static int CELT_ALLOC_FAIL = -7;
  public final static int CELT_GET_MODE_REQUEST = 1;
  public final static int CELT_SET_COMPLEXITY_REQUEST = 2;
  public final static int CELT_SET_PREDICTION_REQUEST = 4;
  public final static int CELT_SET_VBR_RATE_REQUEST = 6;
  public final static int CELT_RESET_STATE_REQUEST = 8;
  public final static int CELT_RESET_STATE = 8;
  public final static int CELT_GET_FRAME_SIZE = 1000;
  public final static int CELT_GET_LOOKAHEAD = 1001;
  public final static int CELT_GET_SAMPLE_RATE = 1003;
  public final static int CELT_GET_BITSTREAM_VERSION = 2000;
}
