/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pcgod.mumbleclient.jni;

public interface celtConstants {
  public final static int CELT_OK = celtJNI.CELT_OK_get();
  public final static int CELT_BAD_ARG = celtJNI.CELT_BAD_ARG_get();
  public final static int CELT_INVALID_MODE = celtJNI.CELT_INVALID_MODE_get();
  public final static int CELT_INTERNAL_ERROR = celtJNI.CELT_INTERNAL_ERROR_get();
  public final static int CELT_CORRUPTED_DATA = celtJNI.CELT_CORRUPTED_DATA_get();
  public final static int CELT_UNIMPLEMENTED = celtJNI.CELT_UNIMPLEMENTED_get();
  public final static int CELT_INVALID_STATE = celtJNI.CELT_INVALID_STATE_get();
  public final static int CELT_ALLOC_FAIL = celtJNI.CELT_ALLOC_FAIL_get();
  public final static int CELT_GET_MODE_REQUEST = celtJNI.CELT_GET_MODE_REQUEST_get();
  public final static int CELT_SET_COMPLEXITY_REQUEST = celtJNI.CELT_SET_COMPLEXITY_REQUEST_get();
  public final static int CELT_SET_PREDICTION_REQUEST = celtJNI.CELT_SET_PREDICTION_REQUEST_get();
  public final static int CELT_SET_VBR_RATE_REQUEST = celtJNI.CELT_SET_VBR_RATE_REQUEST_get();
  public final static int CELT_RESET_STATE_REQUEST = celtJNI.CELT_RESET_STATE_REQUEST_get();
  public final static int CELT_RESET_STATE = celtJNI.CELT_RESET_STATE_get();
  public final static int CELT_GET_FRAME_SIZE = celtJNI.CELT_GET_FRAME_SIZE_get();
  public final static int CELT_GET_LOOKAHEAD = celtJNI.CELT_GET_LOOKAHEAD_get();
  public final static int CELT_GET_SAMPLE_RATE = celtJNI.CELT_GET_SAMPLE_RATE_get();
  public final static int CELT_GET_BITSTREAM_VERSION = celtJNI.CELT_GET_BITSTREAM_VERSION_get();
}
