/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pcgod.mumbleclient.jni;

class celtJNI {
  public final static native long celt_mode_create(int jarg1, int jarg2);
  public final static native void celt_mode_destroy(long jarg1);
  public final static native int celt_mode_info(long jarg1, int jarg2, int[] jarg3);
  public final static native long celt_encoder_create(long jarg1, int jarg2);
  public final static native void celt_encoder_destroy(long jarg1);
  public final static native int celt_encode(long jarg1, short[] jarg2, short[] jarg3, int jarg4);
  public final static native int celt_encoder_ctl(long jarg1, int jarg2, int jarg3);
  public final static native long celt_decoder_create(long jarg1, int jarg2);
  public final static native void celt_decoder_destroy(long jarg1);
  public final static native int celt_decode(long jarg1, short[] jarg2, int jarg3, short[] jarg4);
  public final static native long speex_resampler_init(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native void speex_resampler_destroy(long jarg1);
  public final static native int speex_resampler_process_int(long jarg1, int jarg2, short[] jarg3, int[] jarg4, short[] jarg5, int[] jarg6);
}
